set visualbell
set noswapfile

set iskeyword+=-
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.tmp/*,*/tmp/*,tmp/*,*/temp/*,*/.jhw-cache/*,*/.build/*,*/.meteor/*,*/node_modules/*,*/coverage/*,*/out/*

set grepprg=ack\ --nogroup\ --nocolor

set number

let mapleader = " "


set rtp+=/usr/local/opt/fzf

let g:syntastic_javascript_checkers = ['jsxhint']

let g:jsx_ext_required = 0

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

"save in command mode
nnoremap § :wa

"Paste without moving the cursor
nnoremap <Leader>p p`[
nnoremap <Leader>P P`[

"Delete without yanking
nnoremap <leader>d "_d
xnoremap <leader>d "_d

"Split switching
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Newlines on enter wo insert mode
nmap <S-Enter> O<Esc>
nmap <CR> o<Esc>

"Clear highlights
nnoremap <ESC> :nohlsearch<CR>

"Fugitive
nmap <leader>gb :Gblame<CR>

"FZF
nnoremap <silent> <C-p> :FZF<CR>

" NERDTree
map <leader>n :NERDTreeToggle<CR>:NERDTreeMirror<CR>

" Init ragtag for custom filetypes
autocmd FileType jst call RagtagInit()

" Find scss files
autocmd BufNewFile,BufRead *.scss setf scss

" Autosave on blur
autocmd FocusLost * silent! wa

" improve js (coffee?) highlighting
set lsp=2
hi link jsObjectKey             Identifier
hi link jsNoise                SpecialChar
hi link jsBrackets             SpecialChar




hi link jsParens               SpecialChar
hi link jsBraces               SpecialChar
hi link jsFuncBraces           SpecialChar
hi link jsFuncParens           SpecialChar
hi link jsClassBraces          SpecialChar
hi link jsClassNoise           SpecialChar
hi link jsObjectBraces         SpecialChar
hi link jsObjectSeparator      SpecialChar
hi link jsDestructuringBraces  SpecialChar

let g:lightline = {
      \ 'colorscheme': 'monokai_tasty',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }
set laststatus=2


if has("gui_running")
  set guifont=Inconsolata:h12
endif

if has("gui_macvim")
  " Command-Shift-F on OSX
  map <D-F> :Ack<space>

  " FZF
  map  <D-t> :FZF<CR>
  imap <D-t> <ESC>:FZF<CR>
endif

let g:vim_monokai_tasty_italic = 1
colorscheme vim-monokai-tasty

